apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"    #this will make this storageclass the default storage class
provisioner: example.com/nfs
parameters:
  archiveOnDelete: "false"
