apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
  labels:
    app: department
  namespace: dev  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department
  template:
    metadata:
      labels:
        app: department
    spec:
      containers:
      - name: department
        image: guharoytamajit/department:1.7
#        command: ["sh","-c"]
#        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 8081
        env:
#        - name: APP_HOME
#          value: /usr/app
#        - name: APP_FILE
#          value: department-service-1.0-SNAPSHOT.jar                  
        - name: SPRING_PROFILES_ACTIVE
          value: kube
#        - name: SPRING_CONFIG_LOCATION
#          value: file:/deployments/config/application.yml,file:/deployments/config/application-kube.yml
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password
        volumeMounts:
          - name: application-config 
            mountPath: "/usr/apps/config" 
            readOnly: true
      volumes:
      - name: application-config
        configMap:
          name: spring-app-config 
#          items:
#          - key: application-kube.yml 
#            path: application-kube.yml    
#          - key: application.yml 
#            path: application.yml                
---
apiVersion: v1
kind: Service
metadata:
  name: department
  labels:
    app: department
  namespace: dev  
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: department