apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: employee
  labels:
    app: employee
  namespace: dev  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
      - name: employee
        image: guharoytamajit/employee:1.1
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: employee
  labels:
    app: employee
  namespace: dev  
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: employee