apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization
  labels:
    app: organization
  namespace: dev  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organization
  template:
    metadata:
      labels:
        app: organization
    spec:
      containers:
      - name: organization
        image: guharoytamajit/organization:1.1
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb
              key: database-name
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: organization
  labels:
    app: organization
  namespace: dev  
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: organization